name = "api-lista-contato"
compatibility_date = "2023-12-01"

[vars]
KEY = ""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "lista-contato"
database_id = ""

# [ai]
# binding = "AI"